### ISSUE TITLE
Deleting users / companies when not present anymore?

### ISSUE THREAD

**Issue by marnickmenting** [userlist/userlist-laravel#2]
When syncing using userlist:import, I would like to clean up companies and users that are not present anymore. I deleted the accounts from our app, so they can be safely deleted from Userlist too. Maybe you should add a config setting to choose whether you want to remove non-existing users and/or companies from Userlist.

**Comment by marnickmenting** [comment]
Shall I make a PR?

**Comment by benedikt** [comment]
Hey @marnickmenting,

you're right. Deleting users currently isn't supported by the library. I hope to add this soon.

**Comment by marnickmenting** [comment]
Hi @benedikt ,

I am trying to do this in the code, but get an issue. I call this:

```
app(\Userlist\Laravel\Services\DirectPush::class)->push->users->delete(['identifier' => 'test'])
```

But it gives me an error:

```
PHP Error:  Call to undefined method Userlist\Push\Client::delete() in /var/www/html/vendor/userlist/userlist/src/Push/Relation.php on line 28
```

It seems the delete() method is missing in userlist-php/Push/Client.php, or the wrong instance of Client is passed to userlist-php/Push/Relation.php from userlist-laravel.

If I add this to Push/Client.php:

```
    public function delete($endpoint, $payload = [])
    {
        $this->request('DELETE', $endpoint, $payload);
    }
```

It works, but I wonder why (if?) the vanilla PHP package works without it.

**Comment by benedikt** [comment]
Hi @marnickmenting,

thanks for pointing this out. I just pushed a new version of the userlist-php library that implements the `delete` method. 

Cheers,

Benedikt

**Comment by marnickmenting** [comment]
Great, it works now.

For reference, this is my code to delete users in Userlist when they are deleted in application:

```
use Userlist\Laravel\Services\DirectPush;

class User { // Model class
...
    public static function boot() {
        self::deleting(function (User $model) {
            app(DirectPush::class)->push->users->delete(['identifier' => $model->id]);
        });

        parent::boot();
    }
}
```
