### ISSUE TITLE
Filter users to be sent to Userlist

### ISSUE THREAD

**Issue by marnickmenting** [userlist/userlist-laravel#3]
I only want to send users with a certain role to Userlist. Is there a place where I can add a query that is used in the `userlist:import:users` command?

Example:

```
function filterUserlistUser($query) {
    return $query->hasRole('admin');
}
```

The reason for this is that I want to send campaigns and broadcasts to the admin users (generally the business owners), not their employees. I might exclude them from the front-end in Userlist, but then my account's user limit will be reached soon, and the data will be cluttered.

Shall I write a PR for this?

**Comment by benedikt** [comment]
Hey @marnickmenting. This is already supported. Just change your transforms to return `null` instead of an array.

**Comment by marnickmenting** [comment]
Ah, thanks!
