### ISSUE TITLE
Using in multi-tenancy context

### ISSUE THREAD

**Issue by marnickmenting** [userlist/userlist-laravel#4]
We have a Laravel application that uses hyn/multi-tenancy solution. Any advice on how I should import the users? What I am thinking is rewrite the ImportCommand to loop the tenants before looping the users, like below. But I am not sure if this is the best way.

```
public function handle(Userlist $userlist)
    {
        $this->userlist = $userlist;
        $modelClass = $this->modelClass();

        $this->info("Importing all $modelClass...");

        foreach(Website::cursor() as $website) {
            change_tenant($website); // Switch database connection to tenant db

            foreach ($modelClass::cursor() as $entity) {
                $this->line("Importing $modelClass $entity->id...");
                $this->import($entity);
            }
        }
    }
```

**Comment by benedikt** [comment]
Hey @marnickmenting, 

you're of course free to build your own commands for the import. What you posted looks reasonable. 

The only concern I have is overlapping user ids. If you're not careful you'll import user with id 1 from different accounts which will be merged/overwritten in Userlist. 

Cheers,

Benedikt

**Comment by marnickmenting** [comment]
Thanks. With overlapping user ids, you mean the `identifier` field? I will use `{tenant_id}_{user_id}` as format.
