### ISSUE TITLE
Laravel 10 minimum stability

### ISSUE THREAD

**Issue by danielmlozano** [userlist/userlist-laravel#6]
We're in the process of upgrading our application to use Laravel 10, and we've hit a snag with our Userlist integration using this package. We've noticed that it doesn't have any tags marked as stable versions, nor does its `userlist/userlist` dependency.

With Laravel 10 defaulting to "stable" as the new minimum stability, we're unable to proceed without a stable tag being released. As a result, we'd like to kindly request your assistance in releasing a tag to ensure that anyone using Laravel 10 can continue to use this package without any issues.

Thanks for your help with this, and we're looking forward to hearing from you soon.

**Comment by benedikt** [comment]
Hey @danielmlozano!

Thanks for bringing this to our attention. We just tagged `v0.1.0` of both `userlist/userlist` and `userlist/userlist-laravel`. 

Let me know if this solves the issue.
